import { Faction } from "../models/types"
import Head from "next/head"
import Image from "next/image"

export default function FactionDetail({ faction }: { faction: Faction }) {
	const { homeImage } = faction
	return (
		<>
			<Head>
				<title>Arcadius - {faction.name} </title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col gap-8 overflow-clip">
				<div className="relative flex flex-col h-96 overflow-clip items-center justify-end">
					<div className="absolute h-full w-full bg-gradient-to-t from-gray-900 to-transparent z-10" />
					<h1 className="text-5xl font-semibold z-10 left-0 right-0 mx-auto bottom-32">
						{faction.name}
					</h1>
					<Image
						className="absolute top-1"
						src={homeImage.data}
						alt={homeImage.alt}
					/>
				</div>
				<p>{faction.description}</p>

				<div className="flex flex-col gap-4">
					<h2 className="text-3xl">
						{faction.heroes.length > 1 ? "Heroes" : "Hero"}
					</h2>
					{faction.heroes.map((hero) => {
						const { description, image, name } = hero
						return (
							<div className="flex flex-col gap-4">
								<div
									className="flex flex-row justify-between"
									key={hero.name}
								>
									<Image
										className="w-1/2"
										src={image.data}
										alt={image.alt}
									/>
									<div>
										<h2 className="text-2xl">{name}</h2>
										<label>{description}</label>
									</div>
								</div>
							</div>
						)
					})}
				</div>
			</div>
		</>
	)
}
